image: gitpod/workspace-full

tasks:
  - init: python3 -m venv api/flaskvenv&&source api/flaskvenv/bin/activate&&pip install -r api/requirements.txt&&yarn --cwd frontend
    command: yarn --cwd frontend start
