name: Publish to GHCR

on:  
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/lavalleeale/better-vc/better-vc:latest