name: Publish Docker Image

on:  
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ghcr.io/lavalleeale/better-vc/better-vc:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}